POST http://localhost:3700/login
Content-Type: application/json

{
    "correo": "correo",
    "contrasena": "contrasena"
}

###

POST http://localhost:3700/register
Content-Type: application/json

{
    "nombre": "nombre",
    "apellidos": "apellidos",
    "correo": "correo",
    "contrasena": "contrasena",
    "apodo": "apodo",
    "id_genero": "id_genero",
    "nacimiento": "nacimiento",
    "foto": "foto",
    "carrera": "carrera",
    "facultad": "facultad",
    "especialidad": "especialidad",
    "descripcion": "descripcion",
    "mostrar_nombre": true
}

###

GET http://localhost:3700/usuario
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MmMyMjg3NTA4MWViZThiOTA0OGZiYiIsImlhdCI6MTY5NzM5MTkxNSwiZXhwIjoxNjk3NDc4MzE1fQ.Ve3Qumux9F0tmjANQOCz-GbuMFoXeAAlrn3zhK8B_b4