## Usuarios

POST http://localhost:3700/login
Content-Type: application/json

{
    "correo": "correo",
    "contrasena": "contrasena"
}

###

POST http://localhost:3700/register
Content-Type: application/json

{
    "nombre": "nombre2",
    "apellidos": "apellidos",
    "correo": "correo2",
    "contrasena": "contrasena",
    "apodo": "apodo2",
    "id_genero": "id_genero",
    "nacimiento": "nacimiento",
    "foto": "foto",
    "carrera": "carrera",
    "facultad": "facultad",
    "especialidad": "especialidad",
    "descripcion": "descripcion",
    "mostrar_nombre": true
}

###

GET http://localhost:3700/usuario
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzA1Y2EwZGZiYzFmMjcwN2MwMTBjMSIsImlhdCI6MTY5ODA4ODg3NSwiZXhwIjoxNjk4MTc1Mjc1fQ._0rWGrhELmxT5G36c-cbpFu2EkEDaNZFEgFz2aw-a7s

###

DELETE http://localhost:3700/delete-user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MmMyMjg3NTA4MWViZThiOTA0OGZiYiIsImlhdCI6MTY5NzM5NzUxNSwiZXhwIjoxNjk3NDgzOTE1fQ.wMeY3FCthVD72YMGo1TtdB3evDIXzQgfvlBbHgALmF8

###

PUT http://localhost:3700/update-user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MmM0MjQ2YTcwMDdiOGNhOGQ4ZDU4MyIsImlhdCI6MTY5NzM5OTM3MCwiZXhwIjoxNjk3NDg1NzcwfQ.jHz8RSHCFjKCvp41jY2AlgdSFRSHAwCZpcVSGjIStwg

{
    "nombre": "nombre",
    "apellidos": "apellidos",
    "correo": "correo",
    "contrasena": "contrasena",
    "apodo": "apodo",
    "id_genero": "id_genero",
    "nacimiento": "nacimiento",
    "foto": "foto",
    "carrera": "carrera",
    "facultad": "facultad",
    "especialidad": "especialidad",
    "descripcion": "descripcion",
    "mostrar_nombre": true
}

### Solicitudes

POST http://localhost:3700/save-solicitud/65305c0adfbc1f2707c010bb
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzA1Y2EwZGZiYzFmMjcwN2MwMTBjMSIsImlhdCI6MTY5NzY3MTc2NiwiZXhwIjoxNjk3NzU4MTY2fQ.0mbLEn_m5xVhMLRlLN0xBmR9XtFxsThBlxg_Z8ucC2Q
Content-Type: application/json

{
    "tipo": 0
}

###

DELETE http://localhost:3700/delete-solicitud/65305ca0dfbc1f2707c010c1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzA1YzBhZGZiYzFmMjcwN2MwMTBiYiIsImlhdCI6MTY5NzY2ODEyMywiZXhwIjoxNjk3NzU0NTIzfQ.EuapJXhRsqkCSyH8mXJYOlWrC93FMz8I3Y5sTh11vF0

###

GET http://localhost:3700/getAllSolicitudes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzA1Y2EwZGZiYzFmMjcwN2MwMTBjMSIsImlhdCI6MTY5ODA4ODg3NSwiZXhwIjoxNjk4MTc1Mjc1fQ._0rWGrhELmxT5G36c-cbpFu2EkEDaNZFEgFz2aw-a7s

###

GET http://localhost:3700/getSolicitud/65305c0adfbc1f2707c010bb
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzA1Y2EwZGZiYzFmMjcwN2MwMTBjMSIsImlhdCI6MTY5ODA4ODg3NSwiZXhwIjoxNjk4MTc1Mjc1fQ._0rWGrhELmxT5G36c-cbpFu2EkEDaNZFEgFz2aw-a7s

### GUSTOS

POST http://localhost:3700/save-gusto
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzA1Y2EwZGZiYzFmMjcwN2MwMTBjMSIsImlhdCI6MTY5ODcwMTQxNiwiZXhwIjoxNjk4Nzg3ODE2fQ.GhsJIfMS6E7PFHHfs-K3dttQADax8ECfV_H76oYkGyU
Content-Type: application/json

{
    "tipo" : 0,
    "nombre" : "Hola",
    "subtipo": "aaa",
    "afinidad": "aaa",
    "posesion": "aaaaa",
    "duracion": "aaaaa",
    "conversacion": "aaaa",
    "musica": "aaaa",
    "frecuencia": "aaaa",
    "compania": "aaaa"
}

###

GET http://localhost:3700/gustos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzA1Y2EwZGZiYzFmMjcwN2MwMTBjMSIsImlhdCI6MTY5ODcwMTQxNiwiZXhwIjoxNjk4Nzg3ODE2fQ.GhsJIfMS6E7PFHHfs-K3dttQADax8ECfV_H76oYkGyU

###

GET http://localhost:3700/gusto/654026e2399b9416d1d0be53
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzA1Y2EwZGZiYzFmMjcwN2MwMTBjMSIsImlhdCI6MTY5ODcwMTQxNiwiZXhwIjoxNjk4Nzg3ODE2fQ.GhsJIfMS6E7PFHHfs-K3dttQADax8ECfV_H76oYkGyU

###

DELETE http://localhost:3700/delete-gusto/654026d4399b9416d1d0be4e
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzA1Y2EwZGZiYzFmMjcwN2MwMTBjMSIsImlhdCI6MTY5ODcwMTQxNiwiZXhwIjoxNjk4Nzg3ODE2fQ.GhsJIfMS6E7PFHHfs-K3dttQADax8ECfV_H76oYkGyU

###

PUT http://localhost:3700/update-gusto/654027bd35390724a6bbbed8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzA1Y2EwZGZiYzFmMjcwN2MwMTBjMSIsImlhdCI6MTY5ODcwMTQxNiwiZXhwIjoxNjk4Nzg3ODE2fQ.GhsJIfMS6E7PFHHfs-K3dttQADax8ECfV_H76oYkGyU
Content-Type: application/json

{
    "tipo" : 0,
    "nombre" : "Hola3",
    "subtipo": "aaa",
    "afinidad": "aaa",
    "posesion": "aaaaa",
    "duracion": "aaaaa",
    "conversacion": "aaaa",
    "musica": "aaaa",
    "frecuencia": "aaaa",
    "compania": "aaaa"
}

### MENSAJES

POST http://localhost:3700/mensaje/65305c0adfbc1f2707c010bb
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzAzOTkxZWY1YTNjNmVmMjdkNTFiZiIsImlhdCI6MTY5OTc1NjM2MCwiZXhwIjoxNjk5ODQyNzYwfQ.b9DpJWPt1jplBiREd-SRIjPCc0asLMOaxlLhB3n7p7U
Content-Type: application/json

{
    "text": "holaaaaaaa4"
}

###

GET http://localhost:3700/mensajes-recibidos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzAzOTkxZWY1YTNjNmVmMjdkNTFiZiIsImlhdCI6MTY5OTc1NjQ1OCwiZXhwIjoxNjk5ODQyODU4fQ.RoD6e_8iN6_XRFV4gymiRZQHCa1KRVwexZ1oql0uY3o

###

GET http://localhost:3700/mensajes-emitidos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzAzOTkxZWY1YTNjNmVmMjdkNTFiZiIsImlhdCI6MTY5OTc1NjQ1OCwiZXhwIjoxNjk5ODQyODU4fQ.RoD6e_8iN6_XRFV4gymiRZQHCa1KRVwexZ1oql0uY3o

###

GET http://localhost:3700/mensajes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzAzOTkxZWY1YTNjNmVmMjdkNTFiZiIsImlhdCI6MTY5OTc1NjQ1OCwiZXhwIjoxNjk5ODQyODU4fQ.RoD6e_8iN6_XRFV4gymiRZQHCa1KRVwexZ1oql0uY3o