GET http://localhost:3700/gustos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTEyZGVmNjI4YmY1ZTI0ODNmNDA0ZCIsImlhdCI6MTY5OTgxODk5NCwiZXhwIjoxNjk5OTA1Mzk0fQ.ojaQySrcK1apQCCAcNnY7o3dA3xdP0fof2QKJO_-nVc

###
POST http://localhost:3700/save-gusto
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTEyZGVmNjI4YmY1ZTI0ODNmNDA0ZCIsImlhdCI6MTY5OTgxODk5NCwiZXhwIjoxNjk5OTA1Mzk0fQ.ojaQySrcK1apQCCAcNnY7o3dA3xdP0fof2QKJO_-nVc

{
    "tipo":"valor 1",
    "nombre":"valor 2",
    "subtipo":"valor 3",
    "afinidad":"adsaf",
    "posesion":"asdf",
    "duracion":"asdf",
    "conversacion":"asdf",
    "musica":"asdf",
    "frecuencia":"asdf",
}