GET http://localhost:3700/gusto
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2ZjY2I0YTdhNzI2MWU3NzAzMWY4NCIsImlhdCI6MTY5ODY3OTk5NCwiZXhwIjoxNjk4NzY2Mzk0fQ.PMws7K0lLf8fsuEV9HWNhAsunFnO5R5rwBk2ArGeomI