POST http://localhost:3700/login
Content-Type: application/json

{
    "correo": "20200713@aloe.ulima.edu.pe",
    "contrasena": "holahola"
}

###

POST http://localhost:3700/register
Content-Type: application/json

{
    "nombre": "Sebas",
    "apellidos": "Camayo",
    "correo": "29182713@aloe.ulima.edu.pe",
    "contrasena": "12345678",
    "apodo": "apodo",
    "id_genero": "0",
    "nacimiento": "2002-12-27",
    "foto": "foto",
    "carrera": "carrera",
    "facultad": "2",
    "especialidad": "especialidad",
    "descripcion": "descripcion",
    "mostrar_nombre": true,
    "confirmationCode":"12345678"
}

###

GET http://localhost:3700/usuario
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NWU3YmFkN2Q1ZmVkNmNkYWY0NzI4OCIsImlhdCI6MTcwMDY5MzAzMiwiZXhwIjoxNzAwNzc5NDMyfQ.fzTTlas4Qpg7SeYVjDTNmEKz0iJAfKKrseLZklpL4_8
###
GET http://localhost:3700/find-all-users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NWU3YmFkN2Q1ZmVkNmNkYWY0NzI4OCIsImlhdCI6MTcwMDY5MzAzMiwiZXhwIjoxNzAwNzc5NDMyfQ.fzTTlas4Qpg7SeYVjDTNmEKz0iJAfKKrseLZklpL4_8
###

DELETE http://localhost:3700/delete-user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MmMyMjg3NTA4MWViZThiOTA0OGZiYiIsImlhdCI6MTY5NzM5NzUxNSwiZXhwIjoxNjk3NDgzOTE1fQ.wMeY3FCthVD72YMGo1TtdB3evDIXzQgfvlBbHgALmF8

###

PUT http://localhost:3700/update-user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzBhNWIyNjBjOGExYmNiNmQxNjVlYSIsImlhdCI6MTY5NzY4Njk2MywiZXhwIjoxNjk3NzczMzYzfQ.Jj3MdYHJgStYHsQOs4MNZhNYzcfzqhooYSVPg8gRRiQ

{
    "nombre": "Hitori",
    "apellidos": "Bocchi",
    "correo": "90909090@aloe.ulima.edu.pe",
    "contrasena": "$2b$08$0jojNeRN9nCX/0/LtAs4NuPly5lPn/TdspMMk0WKO9Ix9DzFPFY4K",
    "apodo": "GuitarHero",
    "id_genero": "1",
    "nacimiento": "2004-02-10",
    "foto": "",
    "carrera": "Música",
    "facultad": "0",
    "especialidad": "Guitarra",
    "descripcion": "Sumigod",
    "mostrar_nombre": false
}



###


GET http://localhost:3700/verify-delete-code/12345678
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDk5NDY5MTBiMWQ3MzMxODdhMzI4MSIsImlhdCI6MTY5OTMyNDAzMSwiZXhwIjoxNjk5NDEwNDMxfQ.VoQuKullV_AvMF0XIAMJpV_KteOWk4GcMOYJsVGfE_U